### ISSUE TITLE
TODO: step 2: check issuer

### ISSUE THREAD

**Issue by RangeVsRange** [puiterwijk/flask-oidc#4]
This smells like a massive security flaw. What does it mean? What impact does not checking issuer have? Can flask-oidc be considered secure if it's not checking the issuer?

**Comment by SteelPangolin** [comment]
https://developers.google.com/accounts/docs/OpenIDConnect#validatinganidtoken

Impact is unclear. `flask-oidc` receives ID tokens from Google, over an authenticated TLS connection. It also receives ID tokens from its own signed cookies, but they should only be there if they've been received from Google. I believe the issuer is only important if you're receiving ID tokens from some source other than the IdP.

**Comment by puiterwijk** [comment]
This has been fixed with 8e69fcfe9f52a90eafd36b2a610e1f7d7b23e3fe, and will soon be in a new release.

Not checking the issuer was not a massive issue in this case because the id token is retrieved directly from an endpoint configured in the client_secrets which is an https-only endpoint at Google.
However, it is a minor security issue since you then trust Google to never issue id_tokens for another issuer by accident or something.

Checking the ID token issuer is mostly important if you accept other flows where the id token is provided as part of the return values, which this client does not yet accept.
